### ISSUE TITLE
Implement glfwSetWindowIcon

### ISSUE THREAD

**Issue by zbaylin** [bryphe/reason-glfw#95]
This is a cross-platform way of setting the icon of a GLFW window.

It is documented [here](https://www.glfw.org/docs/latest/group__window.html#gadd7ccd39fe7a7d1f0904666ae5932dc5)

The tricky thing is that GLFW doesn't provide any means for opening a bitmap image and extracting the raw data from it, so either we would have to write our own implementation or use a library.

**Comment by zbaylin** [comment]
We can close this pending the merge of #97

**Comment by bryphe** [comment]
Thanks @zbaylin for fixing #97 !
